###############################################################################
#                                                                                                                                                          #
#                Configuration file for the SvxLink server                                                                           #
#                                                                                                                                                          #
###############################################################################

[GLOBAL]
#MODULE_PATH=/usr/lib/arm-linux-gnueabihf/svxlink
LOGIC_CORE_PATH=/usr/lib/x86_64-linux-gnu/svxlink
LOGICS=ReflectorLogic,UsrpLogic
CFG_DIR=svxlink.d
TIMESTAMP_FORMAT="%c"
CARD_SAMPLE_RATE=48000
CARD_CHANNELS=2
#LOCATION_INFO=LocationInfo
LINKS=LinkToReflector


[ReflectorLogic]
TYPE=ReflectorV2
#DNS_DOMAIN=example.com
HOSTS=0.0.0.0
#this will be the url of the authorised reflector
HOST_PORT=5300
#The port number will be that of the host URL - it may vary
HOST_PRIO=100
HOST_PRIO_INC=1
HOST_WEIGHT=10
CALLSIGN="MYCALL"
#authorised Call of the bridge 
AUTH_KEY="Change this key now"
#authorised key from the Svxreflector admin
JITTER_BUFFER_DELAY=0
DEFAULT_TG=####
#Authorised Talkgroup 
MONITOR_TGS=####
TG_SELECT_TIMEOUT=60
TG_SELECT_INHIBIT_TIMEOUT=0
ANNOUNCE_REMOTE_MIN_INTERVAL=300
EVENT_HANDLER=/usr/share/svxlink/events.tcl
NODE_INFO_FILE=/etc/svxlink/node_info.json
MUTE_FIRST_TX_LOC=0
MUTE_FIRST_TX_REM=0
#TMP_MONITOR_TIMEOUT=3600
UDP_HEARTBEAT_INTERVAL=15
QSY_PENDING_TIMEOUT=15
DEFAULT_LANG=en_GB
#VERBOSE=1

[LinkToReflector]
CONNECT_LOGICS=ReflectorLogic,UsrpLogic
DEFAULT_ACTIVE=1
OPTIONS = DEFAULT_CONNECT,NO_DISCONNECT
TIMEOUT=300
#ACTIVATE_ON_ACTIVITY=RepeaterLogic
